import _ from 'lodash'
import Amplify, { Auth, Hub, Analytics, API, graphqlOperation, Cache, Storage } from 'aws-amplify';


export const getInterestsFromObject = async (interestsObject) => {
  const result = await _.values(interestsObject)
  return result
}

function getKeyByValue(object, value) {
  return Object.keys(object).find(key => object[key] === value);
}

export const getObjectFromInterests = async (interestsArray) => {
  var newObject = {};
  await interestsArray.forEach((item) => {
    newObject.push({
      id: getKeyByValue(INTERESTS_LIST, item),
      label: item
    })
  })
  return newObject
}




export const INTERESTS_LIST = [
 { id: 600, label: 'Accountability' },
 { id: 1, label: 'Accountability in eco-labelling' },
 { id: 2, label: 'Accountability of NGOs' },
 { id: 3, label: 'Accountability of Nonprofit organisations' },
 { id: 4, label: 'Accounting and culture' },
 { id: 5, label: 'Accounting and implementation of sustainable development goals' },
 { id: 6, label: 'Accounting and local community' },
 { id: 7, label: 'Accounting education' },
 { id: 8, label: 'Accounting for externalities' },
 { id: 9, label: 'Accounting literature' },
 { id: 10, label: 'Accounting profession' },
 { id: 11, label: 'Acculturation' },
 { id: 12, label: 'Action research' },
 { id: 13, label: 'Activity-based costing' },
 { id: 14, label: 'Ageing and organisation' },
 { id: 15, label: 'Agent based modelling' },
 { id: 16, label: 'Agri-food supply chain' },
 { id: 17, label: 'Agroecology accounting' },
 { id: 18, label: 'Alternative dispute resolution' },
 { id: 19, label: 'Analysis of corporate disclosures' },
 { id: 20, label: 'Anti- and pro-social employee behaviours' },
 { id: 21, label: 'Anti-corporate campaigns' },
 { id: 22, label: 'Application of Blockchain to accounting' },
 { id: 23, label: 'Applications to management' },
 { id: 24, label: 'Art markets' },
 { id: 25, label: 'Art museums' },
 { id: 26, label: 'Arts and cultural management' },
 { id: 27, label: 'Arts branding' },
 { id: 28, label: 'Arts marketing' },
 { id: 29, label: 'Asset management' },
 { id: 30, label: 'Audience Management' },
 { id: 31, label: 'Audit firms' },
 { id: 32, label: 'Auditing' },
 { id: 33, label: 'Auditing expectations gap' },
 { id: 34, label: 'Bank performance' },
 { id: 35, label: 'Banking and financial markets' },
 { id: 36, label: 'Banks and financial markets' },
 { id: 37, label: 'Barriers and Enablers to the Adoption of New Technologies' },
 { id: 38, label: 'Behavioural Finance' },
 { id: 39, label: 'Big data analytics' },
 { id: 40, label: 'Biodiversity accounting' },
 { id: 41, label: 'Bogus self-employment' },
 { id: 42, label: 'Brand Communities' },
 { id: 43, label: 'Brand Management' },
 { id: 44, label: 'Branding' },
 { id: 45, label: 'Branding and sustainability' },
 { id: 46, label: 'Business and international development' },
 { id: 47, label: 'Business continuity' },
 { id: 48, label: 'Business models' },
 { id: 49, label: 'Capabilities' },
 { id: 50, label: 'Capital allocation practices' },
 { id: 51, label: 'Capital marketing' },
 { id: 52, label: 'Capital structure' },
 { id: 53, label: 'Care cultures' },
 { id: 54, label: 'Care quality and job quality' },
 { id: 55, label: 'Career development' },
 { id: 56, label: 'Change and interventions' },
 { id: 57, label: 'Children and marketing' },
 { id: 58, label: 'Circular economy' },
 { id: 59, label: 'Civil society and accounting' },
 { id: 60, label: 'Classical Marxism and accounting' },
 { id: 61, label: 'Climate change' },
 { id: 62, label: 'Co-operatives' },
 { id: 63, label: 'Cognition' },
 { id: 64, label: 'Collaboration' },
 { id: 65, label: 'Commemoration' },
 { id: 66, label: 'Communication' },
 { id: 67, label: 'Communities of Consumption' },
 { id: 68, label: 'Community festivals' },
 { id: 69, label: 'Community studies' },
 { id: 70, label: 'Competition and market volatility' },
 { id: 71, label: 'Conflict and workplace resistance' },
 { id: 72, label: 'Conflict management' },
 { id: 73, label: 'Consulting' },
 { id: 74, label: 'Consumer buying behaviour' },
 { id: 75, label: 'Consumer perception' },
 { id: 76, label: 'Consumer\'s perceptions of Robots and Artifical Intelligence' },
 { id: 77, label: 'Control systems' },
 { id: 78, label: 'Corporate failure' },
 { id: 79, label: 'Corporate finance' },
 { id: 80, label: 'Corporate finance and governance' },
 { id: 81, label: 'Corporate governance' },
 { id: 82, label: 'Corporate performance and market valuation' },
 { id: 83, label: 'Corporate responsibility' },
 { id: 84, label: 'Corporate social responsibility (CSR)' },
 { id: 85, label: 'Corporate success' },
 { id: 86, label: 'Corporate/business community engagement' },
 { id: 87, label: 'Corruption' },
 { id: 88, label: 'Cost accounting' },
 { id: 89, label: 'Council planning' },
 { id: 90, label: 'Counter and shadow accounting' },
 { id: 91, label: 'Creative and cultural industries' },
 { id: 92, label: 'Creative entrepreneurship' },
 { id: 93, label: 'Creative Industries' },
 { id: 94, label: 'Creative leadership' },
 { id: 95, label: 'Creativity' },
 { id: 96, label: 'Credit unions' },
 { id: 97, label: 'Critical accounting' },
 { id: 98, label: 'Critical management' },
 { id: 99, label: 'Critical psychology' },
 { id: 100, label: 'Critical realism and accounting' },
 { id: 101, label: 'Critical theory' },
 { id: 102, label: 'Cross cultural research in accounting' },
 { id: 103, label: 'Cross-border mergers and acquisitions' },
 { id: 104, label: 'Crowd management' },
 { id: 105, label: 'Cultural differences' },
 { id: 106, label: 'Cultural identity' },
 { id: 107, label: 'Cultural Industries' },
 { id: 108, label: 'Cultural studies' },
 { id: 109, label: 'Culture change' },
 { id: 110, label: 'Curiosity and serendipity in information systems' },
 { id: 111, label: 'Customer Experience' },
 { id: 112, label: 'Decision sciences' },
 { id: 113, label: 'Decision support' },
 { id: 114, label: 'Decision-marking' },
 { id: 115, label: 'Development' },
 { id: 116, label: 'Development of new measures/metrics' },
 { id: 117, label: 'Deviance and ethical behaviour' },
 { id: 118, label: 'Dialogics and accounting' },
 { id: 119, label: 'Digital and social media marketing' },
 { id: 120, label: 'Digital Marketing' },
 { id: 121, label: 'Disability' },
 { id: 122, label: 'Discourse' },
 { id: 123, label: 'Diversity' },
 { id: 124, label: 'Drought' },
 { id: 125, label: 'E-Business' },
 { id: 126, label: 'E-learning' },
 { id: 127, label: 'E-Organisations' },
 { id: 128, label: 'Earnings management' },
 { id: 129, label: 'East Asian consumers' },
 { id: 130, label: 'Eco-civilisation' },
 { id: 131, label: 'Economic development' },
 { id: 132, label: 'Economic restructuring' },
 { id: 133, label: 'Economics of transition in China' },
 { id: 134, label: 'Education' },
 { id: 135, label: 'Education and sustainability' },
 { id: 136, label: 'Emerging market economies' },
 { id: 137, label: 'Emerging market multinationals' },
 { id: 138, label: 'Emotion at work' },
 { id: 139, label: 'Empirical finance' },
 { id: 140, label: 'Employability' },
 { id: 141, label: 'Employee wellbeing' },
 { id: 142, label: 'Employee wellbeing and motivation' },
 { id: 143, label: 'Employees of one-child generation in China' },
 { id: 144, label: 'Employment protection legislation' },
 { id: 145, label: 'Employment relations' },
 { id: 146, label: 'Employment rights' },
 { id: 147, label: 'Employment tribunals' },
 { id: 148, label: 'Energy industry' },
 { id: 149, label: 'Enterprise risk management (ERM)' },
 { id: 150, label: 'Enterprise search' },
 { id: 151, label: 'Entrepreneurial behaviour' },
 { id: 152, label: 'Entrepreneurial economies' },
 { id: 153, label: 'Entrepreneurship' },
 { id: 154, label: 'Entry mode choice' },
 { id: 155, label: 'Environmental accounting' },
 { id: 156, label: 'Environmental economics' },
 { id: 157, label: 'Environmental issues in SMEs' },
 { id: 158, label: 'Environmental management systems' },
 { id: 159, label: 'Environmental performance' },
 { id: 160, label: 'Environmental strategy' },
 { id: 161, label: 'Equality at work' },
 { id: 162, label: 'Escalation of commitment' },
 { id: 163, label: 'European Union social policy' },
 { id: 164, label: 'Evaluation' },
 { id: 165, label: 'Evaluation of information systems' },
 { id: 166, label: 'Everday experiences of organizaing' },
 { id: 167, label: 'Experiential Marketing' },
 { id: 168, label: 'Extinction accounting' },
 { id: 169, label: 'Extraction sector' },
 { id: 170, label: 'Factory work' },
 { id: 171, label: 'Family business' },
 { id: 172, label: 'Family supportive supervisor behaviours' },
 { id: 173, label: 'Fashion Marketing' },
 { id: 174, label: 'Fashion marketing and the circular economy' },
 { id: 175, label: 'Financial crisis' },
 { id: 176, label: 'Financial disclosure using text analysis' },
 { id: 177, label: 'Financial distress' },
 { id: 178, label: 'Financial Inclusion' },
 { id: 179, label: 'Financial Intermediation' },
 { id: 180, label: 'Financial Technology' },
 { id: 181, label: 'Financialisation' },
 { id: 182, label: 'Financialisation of care' },
 { id: 183, label: 'Financialization' },
 { id: 184, label: 'Firm behaviour under imperfect capital markets' },
 { id: 185, label: 'Firm or company performance' },
 { id: 186, label: 'Flexicurity' },
 { id: 187, label: 'Flooding' },
 { id: 188, label: 'Followership' },
 { id: 189, label: 'Forecasting' },
 { id: 190, label: 'Foreign direct investment' },
 { id: 191, label: 'Foreign direct investment (FDI)' },
 { id: 192, label: 'Formality' },
 { id: 193, label: 'Freight fleet operator recognition schemes' },
 { id: 194, label: 'Game theory' },
 { id: 195, label: 'Gender' },
 { id: 196, label: 'Gender and creative labour' },
 { id: 197, label: 'Gender in accounting education or profession' },
 { id: 198, label: 'Gentrification' },
 { id: 199, label: 'Global value Chains and labour' },
 { id: 200, label: 'Governance case study on Tesla or Snap' },
 { id: 201, label: 'Governance of alternative trade organisations' },
 { id: 202, label: 'Government funded or endorsed cultural spaces' },
 { id: 203, label: 'Green Bonds' },
 { id: 204, label: 'Group behaviour' },
 { id: 205, label: 'Habitus' },
 { id: 206, label: 'Health and social care organising' },
 { id: 207, label: 'Health organisations' },
 { id: 208, label: 'Healthcare (re) organisation' },
 { id: 209, label: 'Healthcare management' },
 { id: 210, label: 'History - accounting/administrative' },
 { id: 211, label: 'Household accounting practices' },
 { id: 212, label: 'Household saving and consumption decisions' },
 { id: 213, label: 'Housing finance' },
 { id: 214, label: 'Housing market' },
 { id: 215, label: 'Housing policy' },
 { id: 216, label: 'HR strategy' },
 { id: 217, label: 'Human factors/systems thinking' },
 { id: 218, label: 'Human resource management in China' },
 { id: 219, label: 'Human resources and innovation of Chinese firms' },
 { id: 220, label: 'Hybrid organisations' },
 { id: 221, label: 'Hybrid organising' },
 { id: 222, label: 'Identity' },
 { id: 223, label: 'Illegitimate work tasks' },
 { id: 224, label: 'Imagination' },
 { id: 225, label: 'Impact of trade regulations on livelihoods' },
 { id: 226, label: 'Indexing of corporate performance' },
 { id: 227, label: 'Industrial relations and the law' },
 { id: 228, label: 'Inequalities' },
 { id: 229, label: 'Informal economy' },
 { id: 230, label: 'Information goods' },
 { id: 231, label: 'Information systems and management' },
 { id: 232, label: 'Informational interfaces' },
 { id: 233, label: 'Innovation' },
 { id: 234, label: 'Innovation in social care systems and local provision' },
 { id: 235, label: 'Innovation process' },
 { id: 236, label: 'Innovations' },
 { id: 237, label: 'Institutional abuse and mistreatment' },
 { id: 238, label: 'Institutional change and maintenance' },
 { id: 239, label: 'Institutional theory' },
 { id: 240, label: 'Institutional theory applications into management accounting and risk management' },
 { id: 241, label: 'Institutions' },
 { id: 242, label: 'Institutions and political economy' },
 { id: 243, label: 'Insurance and disaster' },
 { id: 244, label: 'International decision-making' },
 { id: 245, label: 'International development' },
 { id: 246, label: 'International marketing' },
 { id: 247, label: 'International trade' },
 { id: 248, label: 'Internationalisation' },
 { id: 249, label: 'Internationalisation of Chinese firms' },
 { id: 250, label: 'Internationalisation strategies' },
 { id: 251, label: 'Internet of things' },
 { id: 252, label: 'Interventionist research' },
 { id: 253, label: 'Italian Business Economics' },
 { id: 254, label: 'Japan' },
 { id: 255, label: 'Job design' },
 { id: 256, label: 'Job quality' },
 { id: 257, label: 'Knowledge Management' },
 { id: 258, label: 'Knowledge sharing' },
 { id: 259, label: 'Labour administration' },
 { id: 260, label: 'Labour inspection' },
 { id: 261, label: 'Labour markets' },
 { id: 262, label: 'Labour process theory' },
 { id: 263, label: 'Language and translation' },
 { id: 264, label: 'Leader development' },
 { id: 265, label: 'Leader humour' },
 { id: 266, label: 'Leader identity' },
 { id: 267, label: 'Leadership' },
 { id: 268, label: 'Lean' },
 { id: 269, label: 'Lean accounting' },
 { id: 270, label: 'Lean in service environments' },
 { id: 271, label: 'Lean production (service)' },
 { id: 272, label: 'Lean Six Sigma' },
 { id: 273, label: 'Learning' },
 { id: 274, label: 'Learning and reflection' },
 { id: 275, label: 'Location models and problems' },
 { id: 276, label: 'Logistics' },
 { id: 277, label: 'Logistics and reverse logistics' },
 { id: 278, label: 'Logistics workers and labour process' },
 { id: 279, label: 'Low carbon supply chain innovation' },
 { id: 280, label: 'Luxury fashion and sustainability' },
 { id: 281, label: 'Luxury goods' },
 { id: 282, label: 'Luxury marketing and consumption' },
 { id: 283, label: 'Management & Leadership' },
 { id: 284, label: 'Management accounting and change' },
 { id: 285, label: 'Management accounting in modern operational environments' },
 { id: 286, label: 'Management and social change' },
 { id: 287, label: 'Management Education' },
 { id: 288, label: 'Management of public leisure facilites' },
 { id: 289, label: 'Managing absence' },
 { id: 290, label: 'Managing diversity' },
 { id: 291, label: 'Manual work' },
 { id: 292, label: 'Market efficiency' },
 { id: 293, label: 'Market-based accounting' },
 { id: 294, label: 'Marketing to children' },
 { id: 295, label: 'Measurement and management of intangible assets' },
 { id: 296, label: 'Media Industries' },
 { id: 297, label: 'Media Management' },
 { id: 298, label: 'Mediation' },
 { id: 299, label: 'Melas events' },
 { id: 300, label: 'Mergers & Acquisitions' },
 { id: 301, label: 'Mergers and acquisitions' },
 { id: 302, label: 'Mission-driven arts organisations' },
 { id: 303, label: 'Mission-driven organisations' },
 { id: 304, label: 'Multi-criteria decision making problems' },
 { id: 305, label: 'Multinational corporations' },
 { id: 306, label: 'Museums in Eastern and Central Europe' },
 { id: 307, label: 'Museums management' },
 { id: 308, label: 'Natural resource extraction' },
 { id: 309, label: 'Natural resource management (water, land)' },
 { id: 310, label: 'Network design' },
 { id: 311, label: 'New ventures' },
 { id: 312, label: 'Non-governmental organisations and sustainability' },
 { id: 313, label: 'Nonprofit organisations' },
 { id: 314, label: 'Nostalgia' },
 { id: 315, label: 'Occupational psychology' },
 { id: 316, label: 'On-line reviews/EWOM' },
 { id: 317, label: 'Online auctions' },
 { id: 318, label: 'Open book accounting' },
 { id: 319, label: 'Operations management' },
 { id: 320, label: 'Operations research' },
 { id: 321, label: 'Operations strategy' },
 { id: 322, label: 'Optimisation' },
 { id: 323, label: 'Oral history' },
 { id: 324, label: 'Organisational adaptation' },
 { id: 325, label: 'Organisational ambidexterity' },
 { id: 326, label: 'Organisational change' },
 { id: 327, label: 'Organisational climate' },
 { id: 328, label: 'Organisational co-evolution' },
 { id: 329, label: 'Organisational communication' },
 { id: 330, label: 'Organisational culture' },
 { id: 331, label: 'Organisational culture and change' },
 { id: 332, label: 'Organisational interventions' },
 { id: 333, label: 'Organisational learning' },
 { id: 334, label: 'Organisational routines' },
 { id: 335, label: 'Organisational safety' },
 { id: 336, label: 'Organisational sociology' },
 { id: 337, label: 'Organisations' },
 { id: 338, label: 'Organisations of the common good' },
 { id: 339, label: 'Organising history' },
 { id: 340, label: 'Organization theory' },
 { id: 341, label: 'Ownership, organisational structure and corporate governance' },
 { id: 342, label: 'Participatory organisational research methodologies' },
 { id: 343, label: 'Patient care' },
 { id: 344, label: 'Pedagogy' },
 { id: 345, label: 'People and Organisation Development' },
 { id: 346, label: 'Perceived positive work impact' },
 { id: 347, label: 'Perfectionism' },
 { id: 348, label: 'Performance appraisal' },
 { id: 349, label: 'Performance management' },
 { id: 350, label: 'Performance measurement' },
 { id: 351, label: 'Performance related pay' },
 { id: 352, label: 'Philanthropy' },
 { id: 353, label: 'Police studies' },
 { id: 354, label: 'Policing' },
 { id: 355, label: 'Policy and practice' },
 { id: 356, label: 'Political economy of financial services' },
 { id: 357, label: 'Political violence and commerce' },
 { id: 358, label: 'Portfolio analysis' },
 { id: 359, label: 'Portfolio management' },
 { id: 360, label: 'Post-industrial museum' },
 { id: 361, label: 'Post-socialist societies' },
 { id: 362, label: 'Post-socialist society' },
 { id: 363, label: 'Power and politics' },
 { id: 364, label: 'Precarious work' },
 { id: 365, label: 'Price prediction' },
 { id: 366, label: 'Pro- and anti-social employee behaviours' },
 { id: 367, label: 'Production planning and control (MRP, MRPII, ERP, ERPII)' },
 { id: 368, label: 'Professional development in accounting and finance' },
 { id: 369, label: 'Profitability dynamics in emerging markets' },
 { id: 370, label: 'Project performance' },
 { id: 371, label: 'Property' },
 { id: 372, label: 'Property developers' },
 { id: 373, label: 'Property Investment' },
 { id: 374, label: 'Prosocial motivation' },
 { id: 375, label: 'Psychological well-being' },
 { id: 376, label: 'Public accountability' },
 { id: 377, label: 'Public management' },
 { id: 378, label: 'Public policy' },
 { id: 379, label: 'Public private partnerships (PPPs)' },
 { id: 380, label: 'Public sector accounting and new public management' },
 { id: 381, label: 'Public sector effectiveness' },
 { id: 382, label: 'Public sector research establishments' },
 { id: 383, label: 'Public service delivery and organisation' },
 { id: 384, label: 'Public-Private Partnerships (PPPs)' },
 { id: 385, label: 'Qualitative methods' },
 { id: 386, label: 'Qualitative research' },
 { id: 387, label: 'Qualitative research methods' },
 { id: 388, label: 'Quantitative research methods' },
 { id: 389, label: 'Quantitative research methods and statistics' },
 { id: 390, label: 'Real Estate' },
 { id: 391, label: 'Real options' },
 { id: 392, label: 'Reflexivity' },
 { id: 393, label: 'Regional development' },
 { id: 394, label: 'Regional economic eevelopment' },
 { id: 395, label: 'Regional economy' },
 { id: 396, label: 'Relationship marketing' },
 { id: 397, label: 'Religious identity' },
 { id: 398, label: 'Representation of peoples and cultures' },
 { id: 399, label: 'Research practice' },
 { id: 400, label: 'Resilience' },
 { id: 401, label: 'Resistance' },
 { id: 402, label: 'Resistance, power and identity' },
 { id: 403, label: 'Responsible investment' },
 { id: 404, label: 'Restructuring and well-being' },
 { id: 405, label: 'Retail marketing' },
 { id: 406, label: 'Retail returns' },
 { id: 407, label: 'Return-to-work' },
 { id: 408, label: 'Reverse logistics' },
 { id: 409, label: 'Risk governance' },
 { id: 410, label: 'Risk Management' },
 { id: 411, label: 'Routines' },
 { id: 412, label: 'Scale development and psychometrics' },
 { id: 413, label: 'Selection and assessment' },
 { id: 414, label: 'Self-employment' },
 { id: 415, label: 'Sensory marketing' },
 { id: 416, label: 'Services marketing' },
 { id: 417, label: 'Servicescape' },
 { id: 418, label: 'Silence' },
 { id: 419, label: 'Smart meters' },
 { id: 420, label: 'SME (small & medium-sized enterprises)' },
 { id: 421, label: 'SME deviant behaviours' },
 { id: 422, label: 'SME internationalisation' },
 { id: 423, label: 'SME marketing' },
 { id: 424, label: 'SMEs' },
 { id: 425, label: 'Social accounting' },
 { id: 426, label: 'Social and environmental accounting' },
 { id: 427, label: 'Social business behaviour' },
 { id: 428, label: 'Social care workforce and labour arrangements' },
 { id: 429, label: 'Social enterprise' },
 { id: 430, label: 'Social enterprises' },
 { id: 431, label: 'Social entrepreneur' },
 { id: 432, label: 'Social entrepreneurship' },
 { id: 433, label: 'Social housing finance' },
 { id: 434, label: 'Social innovation' },
 { id: 435, label: 'Social media' },
 { id: 436, label: 'Social media marketing' },
 { id: 437, label: 'Social movements and accounting' },
 { id: 438, label: 'Socio-cultural context' },
 { id: 439, label: 'Southern NGOs and social movements' },
 { id: 440, label: 'Spatial interaction theory' },
 { id: 441, label: 'Sponsorship' },
 { id: 442, label: 'Sport' },
 { id: 443, label: 'Sports organisations' },
 { id: 444, label: 'Stakeholder engagement' },
 { id: 445, label: 'Corporate governance in China' },
 { id: 446, label: 'Statistical methods in management' },
 { id: 447, label: 'Strategic management' },
 { id: 448, label: 'Strategic marketing' },
 { id: 449, label: 'Strategy' },
 { id: 450, label: 'Strikes' },
 { id: 451, label: 'Sub-Saharan Africa' },
 { id: 452, label: 'Supply chain accounting' },
 { id: 453, label: 'Supply chain contracts' },
 { id: 454, label: 'Supply chain decision support tools' },
 { id: 455, label: 'Supply chain management' },
 { id: 456, label: 'Supply chains and employment' },
 { id: 457, label: 'Supply chains and logistics globally' },
 { id: 458, label: 'Sustainability' },
 { id: 459, label: 'Sustainability accounting' },
 { id: 460, label: 'Sustainability accounting and accountability' },
 { id: 461, label: 'Sustainability claims and certifications' },
 { id: 462, label: 'Sustainability in accounting' },
 { id: 463, label: 'Sustainability in services and retail' },
 { id: 464, label: 'Sustainability labelling' },
 { id: 465, label: 'Sustainability marketing' },
 { id: 466, label: 'Sustainable careers' },
 { id: 467, label: 'Sustainable cities' },
 { id: 468, label: 'Sustainable Entrepreneurship' },
 { id: 469, label: 'Sustainable fashion' },
 { id: 470, label: 'Sustainable freight transport' },
 { id: 471, label: 'Sustainable livelihoods in food systems' },
 { id: 472, label: 'Sustainable marketing and consumption' },
 { id: 473, label: 'Sustainable tourism management' },
 { id: 474, label: 'Sustainable versus Hedonic Consumption' },
 { id: 475, label: 'Takeover prediction' },
 { id: 476, label: 'Taxation' },
 { id: 477, label: 'Team-working' },
 { id: 478, label: 'Teamworking' },
 { id: 479, label: 'Technology in the workplace' },
 { id: 480, label: 'The dark side of social media' },
 { id: 481, label: 'Theatre management and industry' },
 { id: 482, label: 'Trade unions' },
 { id: 483, label: 'Training' },
 { id: 484, label: 'Training & Development' },
 { id: 485, label: 'Training transfer' },
 { id: 486, label: 'Transformational leadership and well-being' },
 { id: 487, label: 'Transistion and emerging economy contexts' },
 { id: 488, label: 'Translation' },
 { id: 489, label: 'Transparency' },
 { id: 490, label: 'Transport and technology' },
 { id: 491, label: 'Transport planning' },
 { id: 492, label: 'Triple top approach' },
 { id: 493, label: 'UK and EU social policy' },
 { id: 494, label: 'Uncertainty modelling and management' },
 { id: 495, label: 'Undeclared work' },
 { id: 496, label: 'Under-employment' },
 { id: 497, label: 'Universities' },
 { id: 498, label: 'Urban freight/city logistics' },
 { id: 499, label: 'Urban metabolism' },
 { id: 500, label: 'Uses of historic past in the political present' },
 { id: 501, label: 'Value chain analysis' },
 { id: 502, label: 'Varieties of capitalism' },
 { id: 503, label: 'Virtual/telework' },
 { id: 504, label: 'Visitors and engagement at cultural sites' },
 { id: 505, label: 'Visual culture' },
 { id: 506, label: 'Voice and silence' },
 { id: 507, label: 'Voluntary sector' },
 { id: 508, label: 'Volunteers in sport' },
 { id: 509, label: 'Women and accounting' },
 { id: 510, label: 'Women\'s careers' },
 { id: 511, label: 'Work conditions' },
 { id: 512, label: 'Work design' },
 { id: 513, label: 'Work intensification' },
 { id: 514, label: 'Work psychology' },
 { id: 515, label: 'Work-family balance' },
 { id: 516, label: 'Work-life balance' },
 { id: 517, label: 'Workgroup diversity and faultlines' },
 { id: 518, label: 'Working carers' },
 { id: 519, label: 'Working-time' },
 { id: 520, label: 'Workplace conflict' },
 { id: 521, label: 'Workplace learning initiatives' },
 { id: 522, label: 'Workplace management' },
]